name: "Lint JS files"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: ./.github/workflows/npm-install

            - name: Run eslint on changed files
              uses: tj-actions/eslint-changed-files@v11
              with:
                  config_path: ".eslintrc.js"
                  file_extensions: |
                      **/*.js
