name: "Generate Test Coverage Report"

jobs:
    coverage:
        permissions:
            checks: write
            pull-requests: write

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Add test coverage report
              uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  test-script: npm run test:coverage
                  skip-step: install
                  annotations: failed-tests
